"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](fg:orange bg:none)\
[( ($os )($username)) ](fg:base06 bg:orange)\
[](fg:prev_bg bg:yellow)\
[( $directory )](fg:base06 bg:prev_bg)\
[](fg:prev_bg bg:cyan)\
[( ($git_branch )($git_status ))](fg:base06 bg:prev_bg)\
[](fg:prev_bg bg:blue)\
[( \
($c )\
($cpp )\
($elixir )\
($golang )\
($haskell )\
($kotlin )\
($nodejs )\
($python )\
($rust )\
)](fg:base06 bg:prev_bg)\
[](fg:prev_bg bg:base02)\
[( \
($nix_shell )\
($docker_context )\
($conda )\
)](fg:base06 bg:prev_bg)\
[](fg:prev_bg bg:base01)\
[( $time) ](fg:base06 bg:prev_bg)\
[](fg:prev_bg bg:none)\
$line_break\
$character
"""

[os]
disabled = false
style = "fg:prev_fg"
format = '[$symbol]($style bg:prev_bg)'

[os.symbols]
Alpine = ""
Arch = ""
CentOS = ""
Debian = ""
EndeavourOS = ""
Fedora = ""
Linux = ""
NixOS = ""
Windows = ""

[username]
disabled = false
show_always = true
style_root = "fg:prev_fg"
style_user = "fg:prev_fg"
format = '[$user]($style bg:prev_bg)'

[directory]
disabled = false
truncation_length = 3
truncation_symbol = "…/"
style = "fg:prev_fg"
format = '[$path]($style bg:prev_bg)'

[directory.substitutions]
"Documents" = "󰉋"
"Downloads" = "󰉍"
"Music" = "󱍙"
"Pictures" = "󰉏"
"Projects" = "󰴉"

[git_branch]
disabled = false
symbol = ""
style = "fg:prev_fg"
format = '[$symbol $branch(:$remote_branch)]($style bg:prev_bg)'

[git_status]
disabled = false
style = "fg:prev_fg"
format = '[($all_status$ahead_behind)]($style bg:prev_bg)'

[c]
disabled = false
symbol = ""
style = "fg:prev_fg"
format = '[$symbol( $version)]($style bg:prev_bg)'

[cpp]
disabled = false
symbol = ""
style = "fg:prev_fg"
format = '[$symbol( $version)]($style bg:prev_bg)'

[elixir]
disabled = false
symbol = ""
style = "fg:prev_fg"
format = '[$symbol( $version)]($style bg:prev_bg)'

[golang]
disabled = false
symbol = ""
style = "fg:prev_fg"
format = '[$symbol( $version)]($style bg:prev_bg)'

[haskell]
disabled = false
symbol = ""
style = "fg:prev_fg"
format = '[$symbol( $version)]($style bg:prev_bg)'

[kotlin]
disabled = false
symbol = ""
style = "fg:prev_fg"
format = '[$symbol( $version)]($style bg:prev_bg)'

[nodejs]
disabled = false
symbol = ""
style = "fg:prev_fg"
format = '[$symbol( $version)]($style bg:prev_bg)'

[python]
disabled = false
symbol = ""
style = "fg:prev_fg"
format = '[$symbol( $version)]($style bg:prev_bg)'

[rust]
disabled = false
symbol = ""
style = "fg:prev_fg"
format = '[$symbol( $version)]($style bg:prev_bg)'

[nix_shell]
disabled = false
heuristic = false
symbol = ""
style = "fg:prev_fg"
pure_msg = '[pure](fg:prev_fg bg:prev_bg)'
impure_msg = '[impure](fg:prev_fg bg:prev_bg)'
unknown_msg = '[unknown](fg:prev_fg bg:prev_bg)'
format = '[$symbol $state( \($name\))]($style bg:prev_bg)'

[docker_context]
disabled = false
symbol = ""
style = "fg:prev_fg"
format = '[$symbol( $context)]($style bg:prev_bg)'

[conda]
disabled = false
symbol = ""
style = "fg:prev_fg"
format = '[$symbol( $environment)]($style bg:prev_bg)'

[time]
disabled = false
time_format = "%T"
style = "fg:prev_fg"
format = '[( $time)]($style bg:prev_bg)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:green)'
error_symbol = '[](bold fg:red)'
vimcmd_symbol = '[](bold fg:green)'
vimcmd_replace_one_symbol = '[](bold fg:magenta)'
vimcmd_replace_symbol = '[](bold fg:magenta)'
vimcmd_visual_symbol = '[](bold fg:yellow)'
